### ISSUE TITLE
Feedback of Assignment

### ISSUE THREAD

**Issue by aakashchavan-qa** [DeepakGarg1700/automation-assignment#2]
Hi Deepak,

I have reviewed all changes. Please re-run first test case(test1-User-should-successfully-login.js) because i am seeing syntax error in this js file.

```
//Assignment 1
// User should successfully login

module.exports = {
  'login to rtmedia demo' : function (client) {
    client
      .maximizeWindow()  // to maximize the window
      .login('http://demo.rtcamp.com/rtmedia','demo'.'demo') // login
      .assert.visible('.logout') // logout will be present if logged in successfully
      .assert.visible('#ab-pending-notifications') // Successfully pending notification is present

      .end();
  }
};
```

```
OUTPUT

nightwatch --test 

/media/akash/CE86C2D486C2BC69/rtCamp/QA-Assignment/Deepak/automation-assignment/tests/test1-User-should-successfully-login.js:8
      .login('http://demo.rtcamp.com/rtmedia','demo'.'demo') // login
                                                     ^^^^^^

SyntaxError: Unexpected string
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

```

It would be great if you perform more assertions in all test cases.
Fixed this and make sure all test case should be run successfully before adding your code in repository.
Please solve this and let me know.
Thanks.

**Comment by DeepakGarg1700** [comment]
Hello Akash

I have solved the issue, and code is added in repository.

Thanks

Deepak Garg
